version: "3.8"
services:
  vpn:
    build:
      context: .
      args:
        - USERNAME=vpnuser
        - PASSWORD=#qweasd@QWEASD!
        - PORT=9007
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
    network_mode: host
    environment:
      - TZ=Asia/Tehran
    restart: unless-stopped
